# Generated by Django 6.0.4 on 2026-05-17 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquillaje',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2026, 5, 17, 17, 31, 23, 637174)),
            preserve_default=False,
        ),
    ]
